# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 2.7
  - 3.6
  - 3.7
install:
  - pip install cookiecutter
script:
  - cookiecutter . --no-input
